name: flavor
description: Flavor Lib
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  lib_flavor_core:
    path: ../../lib_flavor_core

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
